// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  Composable,
  TDataShape,
  Client,
} from './client';
import type {
  GetBookingNotificationsResponse,
  GetBookingNotificationsData,
  GetBookingNotificationsError,
  ListBranchesResponse,
  ListBranchesData,
  ListBranchesError,
  CreateBranchResponse,
  CreateBranchData,
  CreateBranchError,
  DeleteBranchResponse,
  DeleteBranchData,
  DeleteBranchError,
  GetBranchResponse,
  GetBranchData,
  GetBranchError,
  UpdateBranchResponse,
  UpdateBranchData,
  UpdateBranchError,
  GetNotificationSettingsResponse,
  GetNotificationSettingsData,
  GetNotificationSettingsError,
  GetNotificationTemplatesResponse,
  GetNotificationTemplatesData,
  GetNotificationTemplatesError,
  GetNotificationTemplateResponse,
  GetNotificationTemplateData,
  GetNotificationTemplateError,
  GetScheduledNotificationsResponse,
  GetScheduledNotificationsData,
  GetScheduledNotificationsError,
  GetOrganizationDashboardResponse,
  GetOrganizationDashboardData,
  GetOrganizationDashboardError,
  ListEmployeesResponse,
  ListEmployeesData,
  ListEmployeesError,
  CreateEmployeeResponse,
  CreateEmployeeData,
  CreateEmployeeError,
  DeleteEmployeeResponse,
  DeleteEmployeeData,
  DeleteEmployeeError,
  GetEmployeeResponse,
  GetEmployeeData,
  GetEmployeeError,
  UpdateEmployeeResponse,
  UpdateEmployeeData,
  UpdateEmployeeError,
  UpdateNotificationSettingsResponse,
  UpdateNotificationSettingsData,
  UpdateNotificationSettingsError,
  DeleteNotificationTemplateResponse,
  DeleteNotificationTemplateData,
  DeleteNotificationTemplateError,
  CreateNotificationTemplateResponse,
  CreateNotificationTemplateData,
  CreateNotificationTemplateError,
  UpdateNotificationTemplateResponse,
  UpdateNotificationTemplateData,
  UpdateNotificationTemplateError,
  CreateOrganizationResponse,
  CreateOrganizationData,
  CreateOrganizationError,
  SendBulkNotificationResponse,
  SendBulkNotificationData,
  SendBulkNotificationError,
  ListServicesResponse,
  ListServicesData,
  ListServicesError,
  CreateServiceResponse,
  CreateServiceData,
  CreateServiceError,
  DeleteServiceResponse,
  DeleteServiceData,
  DeleteServiceError,
  GetServiceResponse,
  GetServiceData,
  GetServiceError,
  UpdateServiceResponse,
  UpdateServiceData,
  UpdateServiceError,
  ListTimetablesResponse,
  ListTimetablesData,
  ListTimetablesError,
  CreateTimetableResponse,
  CreateTimetableData,
  CreateTimetableError,
  CreateDayRedefinitionResponse,
  CreateDayRedefinitionData,
  CreateDayRedefinitionError,
  DeleteDayRedefinitionResponse,
  DeleteDayRedefinitionData,
  DeleteDayRedefinitionError,
  DeleteTimetableResponse,
  DeleteTimetableData,
  DeleteTimetableError,
  GetTimetableWithRedefinitionsResponse,
  GetTimetableWithRedefinitionsData,
  GetTimetableWithRedefinitionsError,
  UpdateTimetableResponse,
  UpdateTimetableData,
  UpdateTimetableError,
  LoginPhoneResponse,
  LoginPhoneData,
  LoginPhoneError,
  LoginTelegramResponse,
  LoginTelegramData,
  LoginTelegramError,
  LogoutData,
  LogoutError,
  LogoutAllData,
  LogoutAllError,
  GetProfileResponse,
  GetProfileData,
  GetProfileError,
  UpdateProfileResponse,
  UpdateProfileData,
  UpdateProfileError,
  RefreshResponse,
  RefreshData,
  RefreshError,
  VerifyPhoneResponse,
  VerifyPhoneData,
  VerifyPhoneError,
  VerifyTelegramResponse,
  VerifyTelegramData,
  VerifyTelegramError,
  CreateBookingResponse,
  CreateBookingData,
  CreateBookingError,
  GetBranchesResponse,
  GetBranchesData,
  GetBranchesError,
  GetMastersResponse,
  GetMastersData,
  GetMastersError,
  GetMasterByIdResponse,
  GetMasterByIdData,
  GetMasterByIdError,
  GetOrganizationByNameResponse,
  GetOrganizationByNameData,
  GetOrganizationByNameError,
  GetServicesResponse,
  GetServicesData,
  GetServicesError,
  GetWindowsResponse,
  GetWindowsData,
  GetWindowsError,
} from './types.gen';
import {
  vGetBookingNotificationsResponse,
  vListBranchesResponse,
  vCreateBranchResponse,
  vDeleteBranchResponse,
  vGetBranchResponse,
  vUpdateBranchResponse,
  vGetNotificationSettingsResponse,
  vGetNotificationTemplatesResponse,
  vGetNotificationTemplateResponse,
  vGetScheduledNotificationsResponse,
  vGetOrganizationDashboardResponse,
  vListEmployeesResponse,
  vCreateEmployeeResponse,
  vDeleteEmployeeResponse,
  vGetEmployeeResponse,
  vUpdateEmployeeResponse,
  vUpdateNotificationSettingsResponse,
  vDeleteNotificationTemplateResponse,
  vCreateNotificationTemplateResponse,
  vUpdateNotificationTemplateResponse,
  vCreateOrganizationResponse,
  vSendBulkNotificationResponse,
  vListServicesResponse,
  vCreateServiceResponse,
  vDeleteServiceResponse,
  vGetServiceResponse,
  vUpdateServiceResponse,
  vListTimetablesResponse,
  vCreateTimetableResponse,
  vCreateDayRedefinitionResponse,
  vDeleteDayRedefinitionResponse,
  vDeleteTimetableResponse,
  vGetTimetableWithRedefinitionsResponse,
  vUpdateTimetableResponse,
  vLoginPhoneResponse,
  vLoginTelegramResponse,
  vGetProfileResponse,
  vUpdateProfileResponse,
  vRefreshResponse,
  vVerifyPhoneResponse,
  vVerifyTelegramResponse,
  vCreateBookingResponse,
  vGetBranchesResponse,
  vGetMastersResponse,
  vGetMasterByIdResponse,
  vGetOrganizationByNameResponse,
  vGetServicesResponse,
  vGetWindowsResponse,
} from './valibot.gen';
import * as v from 'valibot';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TComposable extends Composable,
  TData extends TDataShape = TDataShape,
  ResT = unknown,
  DefaultT = undefined,
> = ClientOptions<TComposable, TData, ResT, DefaultT> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getBookingNotifications = <
  TComposable extends Composable,
  DefaultT extends
    GetBookingNotificationsResponse = GetBookingNotificationsResponse,
>(
  options: Options<
    TComposable,
    GetBookingNotificationsData,
    GetBookingNotificationsResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetBookingNotificationsResponse | DefaultT,
    GetBookingNotificationsError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetBookingNotificationsResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/bookings/{booking_id}/notifications',
    ...options,
  });
};

export const listBranches = <
  TComposable extends Composable,
  DefaultT extends ListBranchesResponse = ListBranchesResponse,
>(
  options: Options<
    TComposable,
    ListBranchesData,
    ListBranchesResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    ListBranchesResponse | DefaultT,
    ListBranchesError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vListBranchesResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches',
    ...options,
  });
};

export const createBranch = <
  TComposable extends Composable,
  DefaultT extends CreateBranchResponse = CreateBranchResponse,
>(
  options: Options<
    TComposable,
    CreateBranchData,
    CreateBranchResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateBranchResponse | DefaultT,
    CreateBranchError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateBranchResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const deleteBranch = <
  TComposable extends Composable,
  DefaultT extends DeleteBranchResponse = DeleteBranchResponse,
>(
  options: Options<
    TComposable,
    DeleteBranchData,
    DeleteBranchResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    TComposable,
    DeleteBranchResponse | DefaultT,
    DeleteBranchError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vDeleteBranchResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches/{branch_id}',
    ...options,
  });
};

export const getBranch = <
  TComposable extends Composable,
  DefaultT extends GetBranchResponse = GetBranchResponse,
>(
  options: Options<TComposable, GetBranchData, GetBranchResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetBranchResponse | DefaultT,
    GetBranchError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetBranchResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches/{branch_id}',
    ...options,
  });
};

export const updateBranch = <
  TComposable extends Composable,
  DefaultT extends UpdateBranchResponse = UpdateBranchResponse,
>(
  options: Options<
    TComposable,
    UpdateBranchData,
    UpdateBranchResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    TComposable,
    UpdateBranchResponse | DefaultT,
    UpdateBranchError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vUpdateBranchResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches/{branch_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const getNotificationSettings = <
  TComposable extends Composable,
  DefaultT extends
    GetNotificationSettingsResponse = GetNotificationSettingsResponse,
>(
  options: Options<
    TComposable,
    GetNotificationSettingsData,
    GetNotificationSettingsResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetNotificationSettingsResponse | DefaultT,
    GetNotificationSettingsError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetNotificationSettingsResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches/{branch_id}/notification-settings',
    ...options,
  });
};

export const getNotificationTemplates = <
  TComposable extends Composable,
  DefaultT extends
    GetNotificationTemplatesResponse = GetNotificationTemplatesResponse,
>(
  options: Options<
    TComposable,
    GetNotificationTemplatesData,
    GetNotificationTemplatesResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetNotificationTemplatesResponse | DefaultT,
    GetNotificationTemplatesError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetNotificationTemplatesResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches/{branch_id}/notification-templates',
    ...options,
  });
};

export const getNotificationTemplate = <
  TComposable extends Composable,
  DefaultT extends
    GetNotificationTemplateResponse = GetNotificationTemplateResponse,
>(
  options: Options<
    TComposable,
    GetNotificationTemplateData,
    GetNotificationTemplateResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetNotificationTemplateResponse | DefaultT,
    GetNotificationTemplateError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetNotificationTemplateResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches/{branch_id}/notification-templates/{template_id}',
    ...options,
  });
};

export const getScheduledNotifications = <
  TComposable extends Composable,
  DefaultT extends
    GetScheduledNotificationsResponse = GetScheduledNotificationsResponse,
>(
  options: Options<
    TComposable,
    GetScheduledNotificationsData,
    GetScheduledNotificationsResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetScheduledNotificationsResponse | DefaultT,
    GetScheduledNotificationsError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetScheduledNotificationsResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/branches/{branch_id}/scheduled-notifications',
    ...options,
  });
};

export const getOrganizationDashboard = <
  TComposable extends Composable,
  DefaultT extends
    GetOrganizationDashboardResponse = GetOrganizationDashboardResponse,
>(
  options: Options<
    TComposable,
    GetOrganizationDashboardData,
    GetOrganizationDashboardResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetOrganizationDashboardResponse | DefaultT,
    GetOrganizationDashboardError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetOrganizationDashboardResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/dashboard/{organization_id}',
    ...options,
  });
};

export const listEmployees = <
  TComposable extends Composable,
  DefaultT extends ListEmployeesResponse = ListEmployeesResponse,
>(
  options: Options<
    TComposable,
    ListEmployeesData,
    ListEmployeesResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    ListEmployeesResponse | DefaultT,
    ListEmployeesError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vListEmployeesResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/employees',
    ...options,
  });
};

export const createEmployee = <
  TComposable extends Composable,
  DefaultT extends CreateEmployeeResponse = CreateEmployeeResponse,
>(
  options: Options<
    TComposable,
    CreateEmployeeData,
    CreateEmployeeResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateEmployeeResponse | DefaultT,
    CreateEmployeeError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateEmployeeResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/employees',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const deleteEmployee = <
  TComposable extends Composable,
  DefaultT extends DeleteEmployeeResponse = DeleteEmployeeResponse,
>(
  options: Options<
    TComposable,
    DeleteEmployeeData,
    DeleteEmployeeResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    TComposable,
    DeleteEmployeeResponse | DefaultT,
    DeleteEmployeeError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vDeleteEmployeeResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/employees/{employee_id}',
    ...options,
  });
};

export const getEmployee = <
  TComposable extends Composable,
  DefaultT extends GetEmployeeResponse = GetEmployeeResponse,
>(
  options: Options<TComposable, GetEmployeeData, GetEmployeeResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetEmployeeResponse | DefaultT,
    GetEmployeeError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetEmployeeResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/employees/{employee_id}',
    ...options,
  });
};

export const updateEmployee = <
  TComposable extends Composable,
  DefaultT extends UpdateEmployeeResponse = UpdateEmployeeResponse,
>(
  options: Options<
    TComposable,
    UpdateEmployeeData,
    UpdateEmployeeResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    TComposable,
    UpdateEmployeeResponse | DefaultT,
    UpdateEmployeeError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vUpdateEmployeeResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/employees/{employee_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const updateNotificationSettings = <
  TComposable extends Composable,
  DefaultT extends
    UpdateNotificationSettingsResponse = UpdateNotificationSettingsResponse,
>(
  options: Options<
    TComposable,
    UpdateNotificationSettingsData,
    UpdateNotificationSettingsResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    TComposable,
    UpdateNotificationSettingsResponse | DefaultT,
    UpdateNotificationSettingsError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vUpdateNotificationSettingsResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/notification-settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const deleteNotificationTemplate = <
  TComposable extends Composable,
  DefaultT extends
    DeleteNotificationTemplateResponse = DeleteNotificationTemplateResponse,
>(
  options: Options<
    TComposable,
    DeleteNotificationTemplateData,
    DeleteNotificationTemplateResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    TComposable,
    DeleteNotificationTemplateResponse | DefaultT,
    DeleteNotificationTemplateError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vDeleteNotificationTemplateResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/notification-templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const createNotificationTemplate = <
  TComposable extends Composable,
  DefaultT extends
    CreateNotificationTemplateResponse = CreateNotificationTemplateResponse,
>(
  options: Options<
    TComposable,
    CreateNotificationTemplateData,
    CreateNotificationTemplateResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateNotificationTemplateResponse | DefaultT,
    CreateNotificationTemplateError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateNotificationTemplateResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/notification-templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const updateNotificationTemplate = <
  TComposable extends Composable,
  DefaultT extends
    UpdateNotificationTemplateResponse = UpdateNotificationTemplateResponse,
>(
  options: Options<
    TComposable,
    UpdateNotificationTemplateData,
    UpdateNotificationTemplateResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    TComposable,
    UpdateNotificationTemplateResponse | DefaultT,
    UpdateNotificationTemplateError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vUpdateNotificationTemplateResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/notification-templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const createOrganization = <
  TComposable extends Composable,
  DefaultT extends CreateOrganizationResponse = CreateOrganizationResponse,
>(
  options: Options<
    TComposable,
    CreateOrganizationData,
    CreateOrganizationResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateOrganizationResponse | DefaultT,
    CreateOrganizationError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateOrganizationResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/organizations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const sendBulkNotification = <
  TComposable extends Composable,
  DefaultT extends SendBulkNotificationResponse = SendBulkNotificationResponse,
>(
  options: Options<
    TComposable,
    SendBulkNotificationData,
    SendBulkNotificationResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    SendBulkNotificationResponse | DefaultT,
    SendBulkNotificationError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vSendBulkNotificationResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/send-bulk-notification',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const listServices = <
  TComposable extends Composable,
  DefaultT extends ListServicesResponse = ListServicesResponse,
>(
  options: Options<
    TComposable,
    ListServicesData,
    ListServicesResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    ListServicesResponse | DefaultT,
    ListServicesError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vListServicesResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/services',
    ...options,
  });
};

export const createService = <
  TComposable extends Composable,
  DefaultT extends CreateServiceResponse = CreateServiceResponse,
>(
  options: Options<
    TComposable,
    CreateServiceData,
    CreateServiceResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateServiceResponse | DefaultT,
    CreateServiceError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateServiceResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/services',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const deleteService = <
  TComposable extends Composable,
  DefaultT extends DeleteServiceResponse = DeleteServiceResponse,
>(
  options: Options<
    TComposable,
    DeleteServiceData,
    DeleteServiceResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    TComposable,
    DeleteServiceResponse | DefaultT,
    DeleteServiceError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vDeleteServiceResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/services/{service_id}',
    ...options,
  });
};

export const getService = <
  TComposable extends Composable,
  DefaultT extends GetServiceResponse = GetServiceResponse,
>(
  options: Options<TComposable, GetServiceData, GetServiceResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetServiceResponse | DefaultT,
    GetServiceError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetServiceResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/services/{service_id}',
    ...options,
  });
};

export const updateService = <
  TComposable extends Composable,
  DefaultT extends UpdateServiceResponse = UpdateServiceResponse,
>(
  options: Options<
    TComposable,
    UpdateServiceData,
    UpdateServiceResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    TComposable,
    UpdateServiceResponse | DefaultT,
    UpdateServiceError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vUpdateServiceResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/services/{service_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const listTimetables = <
  TComposable extends Composable,
  DefaultT extends ListTimetablesResponse = ListTimetablesResponse,
>(
  options: Options<
    TComposable,
    ListTimetablesData,
    ListTimetablesResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    ListTimetablesResponse | DefaultT,
    ListTimetablesError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vListTimetablesResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/timetables',
    ...options,
  });
};

export const createTimetable = <
  TComposable extends Composable,
  DefaultT extends CreateTimetableResponse = CreateTimetableResponse,
>(
  options: Options<
    TComposable,
    CreateTimetableData,
    CreateTimetableResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateTimetableResponse | DefaultT,
    CreateTimetableError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateTimetableResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/timetables',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const createDayRedefinition = <
  TComposable extends Composable,
  DefaultT extends
    CreateDayRedefinitionResponse = CreateDayRedefinitionResponse,
>(
  options: Options<
    TComposable,
    CreateDayRedefinitionData,
    CreateDayRedefinitionResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateDayRedefinitionResponse | DefaultT,
    CreateDayRedefinitionError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateDayRedefinitionResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/timetables/redefinitions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const deleteDayRedefinition = <
  TComposable extends Composable,
  DefaultT extends
    DeleteDayRedefinitionResponse = DeleteDayRedefinitionResponse,
>(
  options: Options<
    TComposable,
    DeleteDayRedefinitionData,
    DeleteDayRedefinitionResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    TComposable,
    DeleteDayRedefinitionResponse | DefaultT,
    DeleteDayRedefinitionError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vDeleteDayRedefinitionResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/timetables/redefinitions/{master_id}/{date}',
    ...options,
  });
};

export const deleteTimetable = <
  TComposable extends Composable,
  DefaultT extends DeleteTimetableResponse = DeleteTimetableResponse,
>(
  options: Options<
    TComposable,
    DeleteTimetableData,
    DeleteTimetableResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    TComposable,
    DeleteTimetableResponse | DefaultT,
    DeleteTimetableError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vDeleteTimetableResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/timetables/{master_id}',
    ...options,
  });
};

export const getTimetableWithRedefinitions = <
  TComposable extends Composable,
  DefaultT extends
    GetTimetableWithRedefinitionsResponse = GetTimetableWithRedefinitionsResponse,
>(
  options: Options<
    TComposable,
    GetTimetableWithRedefinitionsData,
    GetTimetableWithRedefinitionsResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetTimetableWithRedefinitionsResponse | DefaultT,
    GetTimetableWithRedefinitionsError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetTimetableWithRedefinitionsResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/timetables/{master_id}',
    ...options,
  });
};

export const updateTimetable = <
  TComposable extends Composable,
  DefaultT extends UpdateTimetableResponse = UpdateTimetableResponse,
>(
  options: Options<
    TComposable,
    UpdateTimetableData,
    UpdateTimetableResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    TComposable,
    UpdateTimetableResponse | DefaultT,
    UpdateTimetableError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vUpdateTimetableResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/admin/timetables/{master_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const loginPhone = <
  TComposable extends Composable,
  DefaultT extends LoginPhoneResponse = LoginPhoneResponse,
>(
  options: Options<TComposable, LoginPhoneData, LoginPhoneResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    LoginPhoneResponse | DefaultT,
    LoginPhoneError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vLoginPhoneResponse, data);
    },
    url: '/api/v1/auth/login/phone',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const loginTelegram = <
  TComposable extends Composable,
  DefaultT extends LoginTelegramResponse = LoginTelegramResponse,
>(
  options: Options<
    TComposable,
    LoginTelegramData,
    LoginTelegramResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    LoginTelegramResponse | DefaultT,
    LoginTelegramError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vLoginTelegramResponse, data);
    },
    url: '/api/v1/auth/login/telegram',
    ...options,
  });
};

export const logout = <TComposable extends Composable, DefaultT = undefined>(
  options: Options<TComposable, LogoutData, unknown, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    unknown | DefaultT,
    LogoutError,
    DefaultT
  >({
    url: '/api/v1/auth/logout',
    ...options,
  });
};

export const logoutAll = <TComposable extends Composable, DefaultT = undefined>(
  options: Options<TComposable, LogoutAllData, unknown, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    unknown | DefaultT,
    LogoutAllError,
    DefaultT
  >({
    url: '/api/v1/auth/logout/all',
    ...options,
  });
};

export const getProfile = <
  TComposable extends Composable,
  DefaultT extends GetProfileResponse = GetProfileResponse,
>(
  options: Options<TComposable, GetProfileData, GetProfileResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetProfileResponse | DefaultT,
    GetProfileError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetProfileResponse, data);
    },
    url: '/api/v1/auth/profile',
    ...options,
  });
};

export const updateProfile = <
  TComposable extends Composable,
  DefaultT extends UpdateProfileResponse = UpdateProfileResponse,
>(
  options: Options<
    TComposable,
    UpdateProfileData,
    UpdateProfileResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).put<
    TComposable,
    UpdateProfileResponse | DefaultT,
    UpdateProfileError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vUpdateProfileResponse, data);
    },
    url: '/api/v1/auth/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const refresh = <
  TComposable extends Composable,
  DefaultT extends RefreshResponse = RefreshResponse,
>(
  options: Options<TComposable, RefreshData, RefreshResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    RefreshResponse | DefaultT,
    RefreshError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vRefreshResponse, data);
    },
    url: '/api/v1/auth/refresh',
    ...options,
  });
};

export const verifyPhone = <
  TComposable extends Composable,
  DefaultT extends VerifyPhoneResponse = VerifyPhoneResponse,
>(
  options: Options<TComposable, VerifyPhoneData, VerifyPhoneResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    VerifyPhoneResponse | DefaultT,
    VerifyPhoneError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vVerifyPhoneResponse, data);
    },
    url: '/api/v1/auth/verify/phone',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const verifyTelegram = <
  TComposable extends Composable,
  DefaultT extends VerifyTelegramResponse = VerifyTelegramResponse,
>(
  options: Options<
    TComposable,
    VerifyTelegramData,
    VerifyTelegramResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    VerifyTelegramResponse | DefaultT,
    VerifyTelegramError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vVerifyTelegramResponse, data);
    },
    url: '/api/v1/auth/verify/telegram',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const createBooking = <
  TComposable extends Composable,
  DefaultT extends CreateBookingResponse = CreateBookingResponse,
>(
  options: Options<
    TComposable,
    CreateBookingData,
    CreateBookingResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    CreateBookingResponse | DefaultT,
    CreateBookingError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vCreateBookingResponse, data);
    },
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/bookings/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const getBranches = <
  TComposable extends Composable,
  DefaultT extends GetBranchesResponse = GetBranchesResponse,
>(
  options: Options<TComposable, GetBranchesData, GetBranchesResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetBranchesResponse | DefaultT,
    GetBranchesError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetBranchesResponse, data);
    },
    url: '/api/v1/bookings/branches',
    ...options,
  });
};

export const getMasters = <
  TComposable extends Composable,
  DefaultT extends GetMastersResponse = GetMastersResponse,
>(
  options: Options<TComposable, GetMastersData, GetMastersResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetMastersResponse | DefaultT,
    GetMastersError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetMastersResponse, data);
    },
    url: '/api/v1/bookings/masters',
    ...options,
  });
};

export const getMasterById = <
  TComposable extends Composable,
  DefaultT extends GetMasterByIdResponse = GetMasterByIdResponse,
>(
  options: Options<
    TComposable,
    GetMasterByIdData,
    GetMasterByIdResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetMasterByIdResponse | DefaultT,
    GetMasterByIdError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetMasterByIdResponse, data);
    },
    url: '/api/v1/bookings/masters/{master_id}',
    ...options,
  });
};

export const getOrganizationByName = <
  TComposable extends Composable,
  DefaultT extends
    GetOrganizationByNameResponse = GetOrganizationByNameResponse,
>(
  options: Options<
    TComposable,
    GetOrganizationByNameData,
    GetOrganizationByNameResponse,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetOrganizationByNameResponse | DefaultT,
    GetOrganizationByNameError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetOrganizationByNameResponse, data);
    },
    url: '/api/v1/bookings/organizations/{organization_name}',
    ...options,
  });
};

export const getServices = <
  TComposable extends Composable,
  DefaultT extends GetServicesResponse = GetServicesResponse,
>(
  options: Options<TComposable, GetServicesData, GetServicesResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetServicesResponse | DefaultT,
    GetServicesError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetServicesResponse, data);
    },
    url: '/api/v1/bookings/services',
    ...options,
  });
};

export const getWindows = <
  TComposable extends Composable,
  DefaultT extends GetWindowsResponse = GetWindowsResponse,
>(
  options: Options<TComposable, GetWindowsData, GetWindowsResponse, DefaultT>,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    GetWindowsResponse | DefaultT,
    GetWindowsError,
    DefaultT
  >({
    responseValidator: async (data) => {
      return await v.parseAsync(vGetWindowsResponse, data);
    },
    url: '/api/v1/bookings/windows',
    ...options,
  });
};
