// This file is auto-generated by @hey-api/openapi-ts

export type AccessToken = {
  accessToken: string;
};

export type ApiError = {
  details?: unknown;
  error: ErrorType;
  message: string;
};

export type BookingOut = {
  branchId: string;
  end: string;
  id: string;
  masterId: string;
  serviceId: string;
  start: string;
};

export type BranchOut = {
  addressInfo?: string | null;
  apartmentNumber: string;
  city: string;
  country: string;
  description: string;
  houseNumber: string;
  id: string;
  name: string;
  region: string;
  street: string;
  timezone: string;
};

export type BulkNotificationError = {
  customerId: string;
  error: string;
};

export type BulkNotificationResponse = {
  /**
   * ID задачи массовой рассылки
   */
  bulkId: string;
  /**
   * Список ошибок для неудачных получателей
   */
  errors: Array<BulkNotificationError>;
  /**
   * Количество неудачных (например, у клиента нет телефона/телеграма)
   */
  failedCount: number;
  /**
   * Время запланированной отправки
   */
  scheduledAt: string;
  /**
   * Количество успешно запланированных уведомлений
   */
  scheduledCount: number;
  /**
   * Общее количество получателей
   */
  totalRecipients: number;
};

export type BulkRecipientStrategy =
  | {
      customerIds: Array<string>;
      type: 'specific';
    }
  | {
      type: 'allCustomers';
    }
  | {
      fromDate: string;
      toDate: string;
      type: 'recentBookings';
    };

export type CreateBookingRequest = {
  branchId: string;
  end: string;
  masterId: string;
  notifyMethods: Array<NotifyMethod>;
  organizationName: string;
  serviceId: string;
  start: string;
};

export type CreateBranchOut = {
  id: string;
};

export type CreateBranchRequest = {
  addressInfo?: string | null;
  apartmentNumber?: string | null;
  city: string;
  country: string;
  description: string;
  houseNumber: string;
  name: string;
  organizationId: string;
  region: string;
  street: string;
  timezone: string;
};

export type CreateDayRedefinitionRequest = {
  date: string;
  masterId: string;
  scheduleDay: ScheduleDayIn;
};

export type CreateEmployeeOut = {
  id: string;
};

export type CreateEmployeeRequest = {
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactTelegram?: string | null;
  roles: Array<EmployeeRole>;
  userId: string;
};

export type CreateNotificationTemplateRequest = {
  body: string;
  branchId: string;
  method: NotifyMethod;
  templateType: NotificationTemplateType;
};

export type CreateOrganizationRequest = {
  description?: string | null;
  displayName: string;
  name: string;
};

export type CreateServiceOut = {
  id: string;
};

export type CreateServiceRequest = {
  description: string;
  displayName: string;
  durationMinutes: number;
  masterId?: string | null;
  price?: string | null;
};

export type CreateTimetableRequest = {
  masterId: string;
  recurrenceCycleStart: string;
  scheduleDays: Array<ScheduleDayIn>;
};

export type DayRedefinitionOut = {
  date: string;
  dayData: unknown;
  masterId: string;
};

export type DeleteNotificationTemplateRequest = {
  templateId: string;
};

export type EmployeeOut = {
  contactEmail: string;
  contactPhone: string;
  contactTelegram: string;
  id: string;
  organizationId: string;
  roles: Array<EmployeeRole>;
  userId: string;
};

export type EmployeeRole =
  | {
      branch_id: string;
      role: 'manager';
    }
  | {
      role: 'master';
    };

export type ErrorType =
  | 'NOT_FOUND'
  | 'BAD_REQUEST'
  | 'INVALID_VERIFICATION_CODE'
  | 'VERIFICATION_CODE_EXPIRED'
  | 'INVALID_TELEGRAM_HASH'
  | 'TELEGRAM_HASH_NOT_VERIFIED'
  | 'INVALID_REFRESH_TOKEN'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'CONFLICT'
  | 'INTERNAL_SERVER'
  | 'RATE_LIMIT_EXCEEDED'
  | 'VALIDATION'
  | 'NOT_IMPLEMENTED';

export type Interval = {
  end: string;
  start: string;
};

export type MasterOut = {
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactTelegram?: string | null;
  firstName: string;
  id: string;
  lastName: string;
  patronymic?: string | null;
};

export type NotificationSettingsResponse = {
  branchId: string;
  createdAt: string;
  criticalThresholdHours: number;
  quietHoursEnd: string;
  quietHoursStart: string;
  smartBoundaryHours: number;
  updatedAt: string;
};

export type NotificationStatus = 'pending' | 'sent' | 'failed' | 'cancelled';

export type NotificationTemplateResponse = {
  body: string;
  branchId: string;
  createdAt: string;
  id: string;
  method: NotifyMethod;
  templateType: NotificationTemplateType;
  updatedAt: string;
};

export type NotificationTemplateType =
  | 'booking_reminder'
  | 'booking_confirmed'
  | 'booking_cancelled'
  | 'booking_rescheduled'
  | 'custom_message';

export type NotifyMethod = 'sms' | 'telegram';

export type OrganizationDashboardOut = {
  active: boolean;
  alLeastOneBranch: boolean;
  alLeastOneMaster: boolean;
  alLeastOneService: boolean;
  alLeastOneTimetable: boolean;
  description: string;
  displayName: string;
  id: string;
  name: string;
};

export type OrganizationOut = {
  description: string;
  displayName: string;
  id: string;
  name: string;
};

export type PhoneLoginOk = {
  message: string;
};

export type PhoneLoginRequest = {
  phone: string;
};

export type PhoneVerifyRequest = {
  code: number;
  phone: string;
};

export type ScheduleDayIn =
  | {
      branch_id: string;
      break_intervals: Array<Interval>;
      dayType: 'weekday';
      working_interval: Interval;
    }
  | {
      dayType: 'weekend';
    };

export type ScheduleDayOut = {
  dayData: unknown;
  dayOrdinal: number;
  masterId: string;
};

export type ScheduledNotificationResponse = {
  actualSendAt: string;
  bookingId: string;
  createdAt: string;
  errorMessage?: string | null;
  id: string;
  method: NotifyMethod;
  scheduledAt: string;
  sentAt?: string | null;
  status: NotificationStatus;
  updatedAt: string;
};

export type SendBulkNotificationRequest = BulkRecipientStrategy & {
  branchId: string;
  message: string;
  method: NotifyMethod;
  /**
   * Время отправки. Если не указано - отправляется немедленно
   */
  scheduledAt?: string | null;
};

export type ServiceOut = {
  description: string;
  durationMinutes: number;
  id: string;
  name: string;
  price?: string | null;
};

export type TelegramAuthRequest = {
  hash: string;
};

export type TelegramVerifyHash = {
  hash: string;
};

export type TimetableOut = {
  masterId: string;
  recurrenceCycleDays: number;
  recurrenceCycleStart: string;
};

export type TimetableWithRedefinitionsOut = {
  redefinitions: Array<DayRedefinitionOut>;
  schedule_days: Array<ScheduleDayOut>;
  timetable: TimetableOut;
};

export type UpdateBranchRequest = {
  /**
   * Address info. Send null to clear, omit to keep unchanged
   */
  addressInfo?: string | null;
  /**
   * Apartment number. Send null to clear, omit to keep unchanged
   */
  apartmentNumber?: string | null;
  city?: string | null;
  country?: string | null;
  description?: string | null;
  houseNumber?: string | null;
  name?: string | null;
  region?: string | null;
  street?: string | null;
  timezone?: string | null;
};

export type UpdateEmployeeRequest = {
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactTelegram?: string | null;
  roles?: Array<EmployeeRole> | null;
  userId?: string | null;
};

export type UpdateNotificationSettingsRequest = {
  branchId: string;
  criticalThresholdHours?: number | null;
  quietHoursEnd?: string | null;
  quietHoursStart?: string | null;
  smartBoundaryHours?: number | null;
};

export type UpdateNotificationTemplateRequest = {
  body?: string | null;
  method?: null | NotifyMethod;
  templateId: string;
  templateType?: null | NotificationTemplateType;
};

export type UpdateProfileRequest = {
  firstName: string;
  lastName: string;
  patronymic?: string | null;
};

export type UpdateServiceRequest = {
  description?: string | null;
  displayName?: string | null;
  durationMinutes?: number | null;
  /**
   * Master ID. Send null to clear, omit to keep unchanged
   */
  masterId?: string | null;
  /**
   * Price. Send null to clear, omit to keep unchanged
   */
  price?: string | null;
};

export type UpdateTimetableRequest = {
  recurrenceCycleStart?: string | null;
  scheduleDays?: Array<ScheduleDayIn> | null;
};

export type UserProfileResponse = {
  firstName: string;
  lastName: string;
  patronymic?: string | null;
};

export type GetBookingNotificationsData = {
  body?: never;
  path: {
    /**
     * Booking ID
     */
    booking_id: string;
  };
  query?: never;
  url: '/api/v1/admin/bookings/{booking_id}/notifications';
};

export type GetBookingNotificationsErrors = {
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root, Owner (organization), or Manager (branch) role
   */
  403: ApiError;
  /**
   * Booking not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetBookingNotificationsError =
  GetBookingNotificationsErrors[keyof GetBookingNotificationsErrors];

export type GetBookingNotificationsResponses = {
  /**
   * Booking notifications retrieved
   */
  200: Array<ScheduledNotificationResponse>;
};

export type GetBookingNotificationsResponse =
  GetBookingNotificationsResponses[keyof GetBookingNotificationsResponses];

export type ListBranchesData = {
  body?: never;
  path: {
    /**
     * Organization ID (optional for filtering)
     */
    organization_id: string | null;
    /**
     * Limit number of results (default: 20, max: 100)
     */
    limit: number | null;
    /**
     * Offset for pagination
     */
    offset: number | null;
  };
  query?: never;
  url: '/api/v1/admin/branches';
};

export type ListBranchesErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (organization), or Master (organization) role
   */
  403: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type ListBranchesError = ListBranchesErrors[keyof ListBranchesErrors];

export type ListBranchesResponses = {
  /**
   * List of branches
   */
  200: Array<BranchOut>;
};

export type ListBranchesResponse =
  ListBranchesResponses[keyof ListBranchesResponses];

export type CreateBranchData = {
  body: CreateBranchRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/branches';
};

export type CreateBranchErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Organization not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateBranchError = CreateBranchErrors[keyof CreateBranchErrors];

export type CreateBranchResponses = {
  /**
   * Branch created
   */
  201: CreateBranchOut;
};

export type CreateBranchResponse =
  CreateBranchResponses[keyof CreateBranchResponses];

export type DeleteBranchData = {
  body?: never;
  path: {
    /**
     * Branch ID
     */
    branch_id: string;
  };
  query?: never;
  url: '/api/v1/admin/branches/{branch_id}';
};

export type DeleteBranchErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type DeleteBranchError = DeleteBranchErrors[keyof DeleteBranchErrors];

export type DeleteBranchResponses = {
  /**
   * Branch deleted
   */
  204: void;
};

export type DeleteBranchResponse =
  DeleteBranchResponses[keyof DeleteBranchResponses];

export type GetBranchData = {
  body?: never;
  path: {
    /**
     * Branch ID
     */
    branch_id: string;
  };
  query?: never;
  url: '/api/v1/admin/branches/{branch_id}';
};

export type GetBranchErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (branch), or Master (organization) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetBranchError = GetBranchErrors[keyof GetBranchErrors];

export type GetBranchResponses = {
  /**
   * Branch details
   */
  200: BranchOut;
};

export type GetBranchResponse = GetBranchResponses[keyof GetBranchResponses];

export type UpdateBranchData = {
  body: UpdateBranchRequest;
  path: {
    /**
     * Branch ID
     */
    branch_id: string;
  };
  query?: never;
  url: '/api/v1/admin/branches/{branch_id}';
};

export type UpdateBranchErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), or Manager (branch) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type UpdateBranchError = UpdateBranchErrors[keyof UpdateBranchErrors];

export type UpdateBranchResponses = {
  /**
   * Branch updated
   */
  200: BranchOut;
};

export type UpdateBranchResponse =
  UpdateBranchResponses[keyof UpdateBranchResponses];

export type GetNotificationSettingsData = {
  body?: never;
  path: {
    /**
     * Branch ID
     */
    branch_id: string;
  };
  query?: never;
  url: '/api/v1/admin/branches/{branch_id}/notification-settings';
};

export type GetNotificationSettingsErrors = {
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root, Owner (organization), or Manager (branch) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetNotificationSettingsError =
  GetNotificationSettingsErrors[keyof GetNotificationSettingsErrors];

export type GetNotificationSettingsResponses = {
  /**
   * Notification settings retrieved
   */
  200: NotificationSettingsResponse;
};

export type GetNotificationSettingsResponse =
  GetNotificationSettingsResponses[keyof GetNotificationSettingsResponses];

export type GetNotificationTemplatesData = {
  body?: never;
  path: {
    /**
     * Branch ID
     */
    branch_id: string;
  };
  query?: never;
  url: '/api/v1/admin/branches/{branch_id}/notification-templates';
};

export type GetNotificationTemplatesErrors = {
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetNotificationTemplatesError =
  GetNotificationTemplatesErrors[keyof GetNotificationTemplatesErrors];

export type GetNotificationTemplatesResponses = {
  /**
   * Notification templates retrieved
   */
  200: Array<NotificationTemplateResponse>;
};

export type GetNotificationTemplatesResponse =
  GetNotificationTemplatesResponses[keyof GetNotificationTemplatesResponses];

export type GetNotificationTemplateData = {
  body?: never;
  path: {
    /**
     * Branch ID
     */
    branch_id: string;
    /**
     * Template ID
     */
    template_id: string;
  };
  query?: never;
  url: '/api/v1/admin/branches/{branch_id}/notification-templates/{template_id}';
};

export type GetNotificationTemplateErrors = {
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Template not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetNotificationTemplateError =
  GetNotificationTemplateErrors[keyof GetNotificationTemplateErrors];

export type GetNotificationTemplateResponses = {
  /**
   * Notification template retrieved
   */
  200: NotificationTemplateResponse;
};

export type GetNotificationTemplateResponse =
  GetNotificationTemplateResponses[keyof GetNotificationTemplateResponses];

export type GetScheduledNotificationsData = {
  body?: never;
  path: {
    /**
     * Branch ID
     */
    branch_id: string;
  };
  query?: never;
  url: '/api/v1/admin/branches/{branch_id}/scheduled-notifications';
};

export type GetScheduledNotificationsErrors = {
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root, Owner (organization), or Manager (branch) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetScheduledNotificationsError =
  GetScheduledNotificationsErrors[keyof GetScheduledNotificationsErrors];

export type GetScheduledNotificationsResponses = {
  /**
   * Scheduled notifications retrieved
   */
  200: Array<ScheduledNotificationResponse>;
};

export type GetScheduledNotificationsResponse =
  GetScheduledNotificationsResponses[keyof GetScheduledNotificationsResponses];

export type GetOrganizationDashboardData = {
  body?: never;
  path: {
    /**
     * Organization ID
     */
    organization_id: string;
  };
  query?: never;
  url: '/api/v1/admin/dashboard/{organization_id}';
};

export type GetOrganizationDashboardErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (organization), or Master (organization) role
   */
  403: ApiError;
  /**
   * Organization not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetOrganizationDashboardError =
  GetOrganizationDashboardErrors[keyof GetOrganizationDashboardErrors];

export type GetOrganizationDashboardResponses = {
  /**
   * Organization dashboard
   */
  200: OrganizationDashboardOut;
};

export type GetOrganizationDashboardResponse =
  GetOrganizationDashboardResponses[keyof GetOrganizationDashboardResponses];

export type ListEmployeesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Organization ID (optional for filtering)
     */
    organization_id?: string | null;
    /**
     * Limit number of results (default: 20, max: 100)
     */
    limit?: number | null;
    /**
     * Offset for pagination
     */
    offset?: number | null;
  };
  url: '/api/v1/admin/employees';
};

export type ListEmployeesErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (organization), or Master (organization) role
   */
  403: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type ListEmployeesError = ListEmployeesErrors[keyof ListEmployeesErrors];

export type ListEmployeesResponses = {
  /**
   * List of employees
   */
  200: Array<EmployeeOut>;
};

export type ListEmployeesResponse =
  ListEmployeesResponses[keyof ListEmployeesResponses];

export type CreateEmployeeData = {
  body: CreateEmployeeRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/employees';
};

export type CreateEmployeeErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Organization not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateEmployeeError =
  CreateEmployeeErrors[keyof CreateEmployeeErrors];

export type CreateEmployeeResponses = {
  /**
   * Employee created
   */
  201: CreateEmployeeOut;
};

export type CreateEmployeeResponse =
  CreateEmployeeResponses[keyof CreateEmployeeResponses];

export type DeleteEmployeeData = {
  body?: never;
  path: {
    /**
     * Employee ID
     */
    employee_id: string;
  };
  query?: never;
  url: '/api/v1/admin/employees/{employee_id}';
};

export type DeleteEmployeeErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Employee not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type DeleteEmployeeError =
  DeleteEmployeeErrors[keyof DeleteEmployeeErrors];

export type DeleteEmployeeResponses = {
  /**
   * Employee deleted
   */
  204: void;
};

export type DeleteEmployeeResponse =
  DeleteEmployeeResponses[keyof DeleteEmployeeResponses];

export type GetEmployeeData = {
  body?: never;
  path: {
    /**
     * Employee ID
     */
    employee_id: string;
  };
  query?: never;
  url: '/api/v1/admin/employees/{employee_id}';
};

export type GetEmployeeErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (organization), or Master (organization) role
   */
  403: ApiError;
  /**
   * Employee not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetEmployeeError = GetEmployeeErrors[keyof GetEmployeeErrors];

export type GetEmployeeResponses = {
  /**
   * Employee details
   */
  200: EmployeeOut;
};

export type GetEmployeeResponse =
  GetEmployeeResponses[keyof GetEmployeeResponses];

export type UpdateEmployeeData = {
  body: UpdateEmployeeRequest;
  path: {
    /**
     * Employee ID
     */
    employee_id: string;
  };
  query?: never;
  url: '/api/v1/admin/employees/{employee_id}';
};

export type UpdateEmployeeErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Employee not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type UpdateEmployeeError =
  UpdateEmployeeErrors[keyof UpdateEmployeeErrors];

export type UpdateEmployeeResponses = {
  /**
   * Employee updated
   */
  200: EmployeeOut;
};

export type UpdateEmployeeResponse =
  UpdateEmployeeResponses[keyof UpdateEmployeeResponses];

export type UpdateNotificationSettingsData = {
  body: UpdateNotificationSettingsRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/notification-settings';
};

export type UpdateNotificationSettingsErrors = {
  /**
   * Invalid request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root, Owner (organization), or Manager (branch) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type UpdateNotificationSettingsError =
  UpdateNotificationSettingsErrors[keyof UpdateNotificationSettingsErrors];

export type UpdateNotificationSettingsResponses = {
  /**
   * Notification settings updated
   */
  200: NotificationSettingsResponse;
};

export type UpdateNotificationSettingsResponse =
  UpdateNotificationSettingsResponses[keyof UpdateNotificationSettingsResponses];

export type DeleteNotificationTemplateData = {
  body: DeleteNotificationTemplateRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/notification-templates';
};

export type DeleteNotificationTemplateErrors = {
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Template not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type DeleteNotificationTemplateError =
  DeleteNotificationTemplateErrors[keyof DeleteNotificationTemplateErrors];

export type DeleteNotificationTemplateResponses = {
  /**
   * Notification template deleted
   */
  204: void;
};

export type DeleteNotificationTemplateResponse =
  DeleteNotificationTemplateResponses[keyof DeleteNotificationTemplateResponses];

export type CreateNotificationTemplateData = {
  body: CreateNotificationTemplateRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/notification-templates';
};

export type CreateNotificationTemplateErrors = {
  /**
   * Invalid request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Template already exists
   */
  409: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateNotificationTemplateError =
  CreateNotificationTemplateErrors[keyof CreateNotificationTemplateErrors];

export type CreateNotificationTemplateResponses = {
  /**
   * Notification template created
   */
  201: NotificationTemplateResponse;
};

export type CreateNotificationTemplateResponse =
  CreateNotificationTemplateResponses[keyof CreateNotificationTemplateResponses];

export type UpdateNotificationTemplateData = {
  body: UpdateNotificationTemplateRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/notification-templates';
};

export type UpdateNotificationTemplateErrors = {
  /**
   * Invalid request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Template not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type UpdateNotificationTemplateError =
  UpdateNotificationTemplateErrors[keyof UpdateNotificationTemplateErrors];

export type UpdateNotificationTemplateResponses = {
  /**
   * Notification template updated
   */
  200: NotificationTemplateResponse;
};

export type UpdateNotificationTemplateResponse =
  UpdateNotificationTemplateResponses[keyof UpdateNotificationTemplateResponses];

export type CreateOrganizationData = {
  body: CreateOrganizationRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/organizations';
};

export type CreateOrganizationErrors = {
  /**
   * Invalid request data
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Organization name already exists
   */
  409: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateOrganizationError =
  CreateOrganizationErrors[keyof CreateOrganizationErrors];

export type CreateOrganizationResponses = {
  /**
   * Organization created successfully
   */
  201: OrganizationOut;
};

export type CreateOrganizationResponse =
  CreateOrganizationResponses[keyof CreateOrganizationResponses];

export type SendBulkNotificationData = {
  body: SendBulkNotificationRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/send-bulk-notification';
};

export type SendBulkNotificationErrors = {
  /**
   * Invalid request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root, Owner (organization), or Manager (branch) role
   */
  403: ApiError;
  /**
   * Branch not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type SendBulkNotificationError =
  SendBulkNotificationErrors[keyof SendBulkNotificationErrors];

export type SendBulkNotificationResponses = {
  /**
   * Bulk notification sent
   */
  200: BulkNotificationResponse;
};

export type SendBulkNotificationResponse =
  SendBulkNotificationResponses[keyof SendBulkNotificationResponses];

export type ListServicesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Organization ID (optional for filtering)
     */
    organization_id?: string | null;
    /**
     * Limit number of results (default: 20, max: 100)
     */
    limit?: number | null;
    /**
     * Offset for pagination
     */
    offset?: number | null;
  };
  url: '/api/v1/admin/services';
};

export type ListServicesErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root, Owner (organization), Manager (organization), or Master (organization) role
   */
  403: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type ListServicesError = ListServicesErrors[keyof ListServicesErrors];

export type ListServicesResponses = {
  /**
   * List of services
   */
  200: Array<ServiceOut>;
};

export type ListServicesResponse =
  ListServicesResponses[keyof ListServicesResponses];

export type CreateServiceData = {
  body: CreateServiceRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/services';
};

export type CreateServiceErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Organization not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateServiceError = CreateServiceErrors[keyof CreateServiceErrors];

export type CreateServiceResponses = {
  /**
   * Service created
   */
  201: CreateServiceOut;
};

export type CreateServiceResponse =
  CreateServiceResponses[keyof CreateServiceResponses];

export type DeleteServiceData = {
  body?: never;
  path: {
    /**
     * Service ID
     */
    service_id: string;
  };
  query?: never;
  url: '/api/v1/admin/services/{service_id}';
};

export type DeleteServiceErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Service not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type DeleteServiceError = DeleteServiceErrors[keyof DeleteServiceErrors];

export type DeleteServiceResponses = {
  /**
   * Service deleted
   */
  204: void;
};

export type DeleteServiceResponse =
  DeleteServiceResponses[keyof DeleteServiceResponses];

export type GetServiceData = {
  body?: never;
  path: {
    /**
     * Service ID
     */
    service_id: string;
  };
  query?: never;
  url: '/api/v1/admin/services/{service_id}';
};

export type GetServiceErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root, Owner (organization), Manager (organization), or Master (organization) role
   */
  403: ApiError;
  /**
   * Service not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetServiceError = GetServiceErrors[keyof GetServiceErrors];

export type GetServiceResponses = {
  /**
   * Service details
   */
  200: ServiceOut;
};

export type GetServiceResponse = GetServiceResponses[keyof GetServiceResponses];

export type UpdateServiceData = {
  body: UpdateServiceRequest;
  path: {
    /**
     * Service ID
     */
    service_id: string;
  };
  query?: never;
  url: '/api/v1/admin/services/{service_id}';
};

export type UpdateServiceErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - requires Root or Owner (organization) role
   */
  403: ApiError;
  /**
   * Service not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type UpdateServiceError = UpdateServiceErrors[keyof UpdateServiceErrors];

export type UpdateServiceResponses = {
  /**
   * Service updated
   */
  200: ServiceOut;
};

export type UpdateServiceResponse =
  UpdateServiceResponses[keyof UpdateServiceResponses];

export type ListTimetablesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Organization ID (optional for filtering)
     */
    organization_id?: string | null;
    /**
     * Limit number of results (default: 20, max: 100)
     */
    limit?: number | null;
    /**
     * Offset for pagination
     */
    offset?: number | null;
  };
  url: '/api/v1/admin/timetables';
};

export type ListTimetablesErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (organization), or Master (organization) role
   */
  403: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type ListTimetablesError =
  ListTimetablesErrors[keyof ListTimetablesErrors];

export type ListTimetablesResponses = {
  /**
   * List of timetables
   */
  200: Array<TimetableOut>;
};

export type ListTimetablesResponse =
  ListTimetablesResponses[keyof ListTimetablesResponses];

export type CreateTimetableData = {
  body: CreateTimetableRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/timetables';
};

export type CreateTimetableErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (branch), or Master (own schedule) role
   */
  403: ApiError;
  /**
   * Master not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateTimetableError =
  CreateTimetableErrors[keyof CreateTimetableErrors];

export type CreateTimetableResponses = {
  /**
   * Timetable created
   */
  204: void;
};

export type CreateTimetableResponse =
  CreateTimetableResponses[keyof CreateTimetableResponses];

export type CreateDayRedefinitionData = {
  body: CreateDayRedefinitionRequest;
  path?: never;
  query?: never;
  url: '/api/v1/admin/timetables/redefinitions';
};

export type CreateDayRedefinitionErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (branch), or Master (own schedule) role
   */
  403: ApiError;
  /**
   * Master not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateDayRedefinitionError =
  CreateDayRedefinitionErrors[keyof CreateDayRedefinitionErrors];

export type CreateDayRedefinitionResponses = {
  /**
   * Day redefinition created
   */
  204: void;
};

export type CreateDayRedefinitionResponse =
  CreateDayRedefinitionResponses[keyof CreateDayRedefinitionResponses];

export type DeleteDayRedefinitionData = {
  body?: never;
  path: {
    /**
     * Master ID
     */
    master_id: string;
    /**
     * Date of the redefinition
     */
    date: string;
  };
  query?: never;
  url: '/api/v1/admin/timetables/redefinitions/{master_id}/{date}';
};

export type DeleteDayRedefinitionErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (branch), or Master (own schedule) role
   */
  403: ApiError;
  /**
   * Day redefinition not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type DeleteDayRedefinitionError =
  DeleteDayRedefinitionErrors[keyof DeleteDayRedefinitionErrors];

export type DeleteDayRedefinitionResponses = {
  /**
   * Day redefinition deleted
   */
  204: void;
};

export type DeleteDayRedefinitionResponse =
  DeleteDayRedefinitionResponses[keyof DeleteDayRedefinitionResponses];

export type DeleteTimetableData = {
  body?: never;
  path: {
    /**
     * Master ID
     */
    master_id: string;
  };
  query?: never;
  url: '/api/v1/admin/timetables/{master_id}';
};

export type DeleteTimetableErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), or Manager (branch) role
   */
  403: ApiError;
  /**
   * Timetable not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type DeleteTimetableError =
  DeleteTimetableErrors[keyof DeleteTimetableErrors];

export type DeleteTimetableResponses = {
  /**
   * Timetable deleted
   */
  204: void;
};

export type DeleteTimetableResponse =
  DeleteTimetableResponses[keyof DeleteTimetableResponses];

export type GetTimetableWithRedefinitionsData = {
  body?: never;
  path: {
    /**
     * Master ID
     */
    master_id: string;
  };
  query?: never;
  url: '/api/v1/admin/timetables/{master_id}';
};

export type GetTimetableWithRedefinitionsErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (branch), or Master (own schedule) role
   */
  403: ApiError;
  /**
   * Timetable not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetTimetableWithRedefinitionsError =
  GetTimetableWithRedefinitionsErrors[keyof GetTimetableWithRedefinitionsErrors];

export type GetTimetableWithRedefinitionsResponses = {
  /**
   * Timetable with schedule days and redefinitions
   */
  200: TimetableWithRedefinitionsOut;
};

export type GetTimetableWithRedefinitionsResponse =
  GetTimetableWithRedefinitionsResponses[keyof GetTimetableWithRedefinitionsResponses];

export type UpdateTimetableData = {
  body: UpdateTimetableRequest;
  path: {
    /**
     * Master ID
     */
    master_id: string;
  };
  query?: never;
  url: '/api/v1/admin/timetables/{master_id}';
};

export type UpdateTimetableErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Forbidden - Requires Root, Owner (organization), Manager (branch), or Master (own schedule) role
   */
  403: ApiError;
  /**
   * Timetable not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type UpdateTimetableError =
  UpdateTimetableErrors[keyof UpdateTimetableErrors];

export type UpdateTimetableResponses = {
  /**
   * Timetable updated
   */
  200: TimetableOut;
};

export type UpdateTimetableResponse =
  UpdateTimetableResponses[keyof UpdateTimetableResponses];

export type LoginPhoneData = {
  body: PhoneLoginRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login/phone';
};

export type LoginPhoneErrors = {
  /**
   * Too many requests
   */
  429: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type LoginPhoneError = LoginPhoneErrors[keyof LoginPhoneErrors];

export type LoginPhoneResponses = {
  /**
   * Verification code sent
   */
  200: PhoneLoginOk;
};

export type LoginPhoneResponse = LoginPhoneResponses[keyof LoginPhoneResponses];

export type LoginTelegramData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login/telegram';
};

export type LoginTelegramErrors = {
  /**
   * Too many requests
   */
  429: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type LoginTelegramError = LoginTelegramErrors[keyof LoginTelegramErrors];

export type LoginTelegramResponses = {
  /**
   * Hash for verification
   */
  200: TelegramVerifyHash;
};

export type LoginTelegramResponse =
  LoginTelegramResponses[keyof LoginTelegramResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type LogoutErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Logout successful
   */
  200: unknown;
};

export type LogoutAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout/all';
};

export type LogoutAllErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type LogoutAllError = LogoutAllErrors[keyof LogoutAllErrors];

export type LogoutAllResponses = {
  /**
   * Logout from all devices successful
   */
  200: unknown;
};

export type GetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/profile';
};

export type GetProfileErrors = {
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Profile not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
  /**
   * Profile retrieved successfully
   */
  200: UserProfileResponse;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type UpdateProfileData = {
  body: UpdateProfileRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/profile';
};

export type UpdateProfileErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized
   */
  401: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
  /**
   * Profile updated successfully
   */
  200: UserProfileResponse;
};

export type UpdateProfileResponse =
  UpdateProfileResponses[keyof UpdateProfileResponses];

export type RefreshData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/refresh';
};

export type RefreshErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
  /**
   * Token refreshed
   */
  200: AccessToken;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type VerifyPhoneData = {
  body: PhoneVerifyRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/verify/phone';
};

export type VerifyPhoneErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type VerifyPhoneError = VerifyPhoneErrors[keyof VerifyPhoneErrors];

export type VerifyPhoneResponses = {
  /**
   * Verification successful
   */
  200: AccessToken;
};

export type VerifyPhoneResponse =
  VerifyPhoneResponses[keyof VerifyPhoneResponses];

export type VerifyTelegramData = {
  body: TelegramAuthRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/verify/telegram';
};

export type VerifyTelegramErrors = {
  /**
   * Verification failed
   */
  400: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type VerifyTelegramError =
  VerifyTelegramErrors[keyof VerifyTelegramErrors];

export type VerifyTelegramResponses = {
  /**
   * Verification successful
   */
  200: AccessToken;
};

export type VerifyTelegramResponse =
  VerifyTelegramResponses[keyof VerifyTelegramResponses];

export type CreateBookingData = {
  body: CreateBookingRequest;
  path?: never;
  query?: never;
  url: '/api/v1/bookings/';
};

export type CreateBookingErrors = {
  /**
   * Bad request
   */
  400: ApiError;
  /**
   * Unauthorized - Authentication required
   */
  401: ApiError;
  /**
   * Service, branch or master not found
   */
  404: Array<ApiError>;
  /**
   * Already booked
   */
  409: Array<ApiError>;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type CreateBookingError = CreateBookingErrors[keyof CreateBookingErrors];

export type CreateBookingResponses = {
  /**
   * Booking created
   */
  201: Array<BookingOut>;
};

export type CreateBookingResponse =
  CreateBookingResponses[keyof CreateBookingResponses];

export type GetBranchesData = {
  body?: never;
  path?: never;
  query: {
    organizationName: string;
    masters?: Array<string>;
  };
  url: '/api/v1/bookings/branches';
};

export type GetBranchesErrors = {
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetBranchesError = GetBranchesErrors[keyof GetBranchesErrors];

export type GetBranchesResponses = {
  /**
   * List of branches
   */
  200: Array<BranchOut>;
};

export type GetBranchesResponse =
  GetBranchesResponses[keyof GetBranchesResponses];

export type GetMastersData = {
  body?: never;
  path?: never;
  query: {
    organizationName: string;
    branches?: Array<string>;
    services?: Array<string>;
  };
  url: '/api/v1/bookings/masters';
};

export type GetMastersErrors = {
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetMastersError = GetMastersErrors[keyof GetMastersErrors];

export type GetMastersResponses = {
  /**
   * List of masters
   */
  200: Array<MasterOut>;
};

export type GetMastersResponse = GetMastersResponses[keyof GetMastersResponses];

export type GetMasterByIdData = {
  body?: never;
  path: {
    /**
     * Master id
     */
    master_id: string;
  };
  query?: never;
  url: '/api/v1/bookings/masters/{master_id}';
};

export type GetMasterByIdErrors = {
  /**
   * Master not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetMasterByIdError = GetMasterByIdErrors[keyof GetMasterByIdErrors];

export type GetMasterByIdResponses = {
  /**
   * Master with ID
   */
  200: MasterOut;
};

export type GetMasterByIdResponse =
  GetMasterByIdResponses[keyof GetMasterByIdResponses];

export type GetOrganizationByNameData = {
  body?: never;
  path: {
    /**
     * Organization name
     */
    organization_name: string;
  };
  query?: never;
  url: '/api/v1/bookings/organizations/{organization_name}';
};

export type GetOrganizationByNameErrors = {
  /**
   * Organization not found
   */
  404: ApiError;
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetOrganizationByNameError =
  GetOrganizationByNameErrors[keyof GetOrganizationByNameErrors];

export type GetOrganizationByNameResponses = {
  /**
   * Organization with name
   */
  200: OrganizationOut;
};

export type GetOrganizationByNameResponse =
  GetOrganizationByNameResponses[keyof GetOrganizationByNameResponses];

export type GetServicesData = {
  body?: never;
  path?: never;
  query: {
    organizationName: string;
    masters?: Array<string>;
  };
  url: '/api/v1/bookings/services';
};

export type GetServicesErrors = {
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetServicesError = GetServicesErrors[keyof GetServicesErrors];

export type GetServicesResponses = {
  /**
   * List of services
   */
  200: Array<ServiceOut>;
};

export type GetServicesResponse =
  GetServicesResponses[keyof GetServicesResponses];

export type GetWindowsData = {
  body?: never;
  path?: never;
  query: {
    organizationName: string;
    serviceId: string;
    masters: Array<string>;
    branches: Array<string>;
    minDatetime: string;
    maxDatetime: string;
  };
  url: '/api/v1/bookings/windows';
};

export type GetWindowsErrors = {
  /**
   * Internal server error
   */
  500: ApiError;
};

export type GetWindowsError = GetWindowsErrors[keyof GetWindowsErrors];

export type GetWindowsResponses = {
  /**
   * List of branches
   */
  200: Array<BranchOut>;
};

export type GetWindowsResponse = GetWindowsResponses[keyof GetWindowsResponses];

export type ClientOptions = {
  baseURL: 'http://localhost:3222' | (string & {});
};
