// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vAccessToken = v.object({
  accessToken: v.string(),
});

export const vApiError = v.object({
  details: v.optional(v.unknown()),
  error: v.string(),
  message: v.string(),
});

export const vBookingOut = v.object({
  branchId: v.pipe(v.string(), v.uuid()),
  end: v.pipe(v.string(), v.isoTimestamp()),
  id: v.pipe(v.string(), v.uuid()),
  masterId: v.pipe(v.string(), v.uuid()),
  serviceId: v.pipe(v.string(), v.uuid()),
  start: v.pipe(v.string(), v.isoTimestamp()),
});

export const vBranchOut = v.object({
  addressInfo: v.optional(v.union([v.string(), v.null()])),
  apartmentNumber: v.string(),
  city: v.string(),
  country: v.string(),
  description: v.string(),
  houseNumber: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  region: v.string(),
  street: v.string(),
  timezone: v.string(),
});

export const vBulkNotificationError = v.object({
  customerId: v.pipe(v.string(), v.uuid()),
  error: v.string(),
});

export const vBulkNotificationResponse = v.object({
  bulkId: v.pipe(v.string(), v.uuid()),
  errors: v.array(vBulkNotificationError),
  failedCount: v.pipe(v.number(), v.integer(), v.minValue(0)),
  scheduledAt: v.string(),
  scheduledCount: v.pipe(v.number(), v.integer(), v.minValue(0)),
  totalRecipients: v.pipe(v.number(), v.integer(), v.minValue(0)),
});

export const vBulkRecipientStrategy = v.union([
  v.object({
    customerIds: v.array(v.pipe(v.string(), v.uuid())),
    type: v.picklist(['specific']),
  }),
  v.object({
    type: v.picklist(['allCustomers']),
  }),
  v.object({
    fromDate: v.string(),
    toDate: v.string(),
    type: v.picklist(['recentBookings']),
  }),
]);

export const vNotifyMethod = v.picklist(['sms', 'telegram']);

export const vCreateBookingRequest = v.object({
  branchId: v.pipe(v.string(), v.uuid()),
  end: v.pipe(v.string(), v.isoTimestamp()),
  masterId: v.pipe(v.string(), v.uuid()),
  notifyMethods: v.array(vNotifyMethod),
  organizationName: v.string(),
  serviceId: v.pipe(v.string(), v.uuid()),
  start: v.pipe(v.string(), v.isoTimestamp()),
});

export const vCreateBranchOut = v.object({
  id: v.pipe(v.string(), v.uuid()),
});

export const vCreateBranchRequest = v.object({
  addressInfo: v.optional(v.union([v.string(), v.null()])),
  apartmentNumber: v.optional(v.union([v.string(), v.null()])),
  city: v.string(),
  country: v.string(),
  description: v.string(),
  houseNumber: v.string(),
  name: v.string(),
  organizationId: v.pipe(v.string(), v.uuid()),
  region: v.string(),
  street: v.string(),
  timezone: v.string(),
});

export const vInterval = v.object({
  end: v.pipe(v.string(), v.isoTimestamp()),
  start: v.pipe(v.string(), v.isoTimestamp()),
});

export const vScheduleDayIn = v.union([
  v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
    break_intervals: v.array(vInterval),
    dayType: v.picklist(['weekday']),
    working_interval: vInterval,
  }),
  v.object({
    dayType: v.picklist(['weekend']),
  }),
]);

export const vCreateDayRedefinitionRequest = v.object({
  date: v.pipe(v.string(), v.isoDate()),
  masterId: v.pipe(v.string(), v.uuid()),
  scheduleDay: vScheduleDayIn,
});

export const vCreateEmployeeOut = v.object({
  id: v.pipe(v.string(), v.uuid()),
});

export const vEmployeeRole = v.union([
  v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
    role: v.picklist(['manager']),
  }),
  v.object({
    role: v.picklist(['master']),
  }),
]);

export const vCreateEmployeeRequest = v.object({
  contactEmail: v.optional(v.union([v.string(), v.null()])),
  contactPhone: v.optional(v.union([v.string(), v.null()])),
  contactTelegram: v.optional(v.union([v.string(), v.null()])),
  roles: v.array(vEmployeeRole),
  userId: v.pipe(v.string(), v.uuid()),
});

export const vNotificationTemplateType = v.picklist([
  'booking_reminder',
  'booking_confirmed',
  'booking_cancelled',
  'booking_rescheduled',
  'custom_message',
]);

export const vCreateNotificationTemplateRequest = v.object({
  body: v.string(),
  branchId: v.pipe(v.string(), v.uuid()),
  method: vNotifyMethod,
  templateType: vNotificationTemplateType,
});

export const vCreateOrganizationRequest = v.object({
  description: v.optional(v.union([v.string(), v.null()])),
  displayName: v.string(),
  name: v.string(),
});

export const vCreateServiceOut = v.object({
  id: v.pipe(v.string(), v.uuid()),
});

export const vCreateServiceRequest = v.object({
  description: v.string(),
  displayName: v.string(),
  durationMinutes: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
    v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
  ),
  masterId: v.optional(v.union([v.pipe(v.string(), v.uuid()), v.null()])),
  price: v.optional(v.union([v.string(), v.null()])),
});

export const vCreateTimetableRequest = v.object({
  masterId: v.pipe(v.string(), v.uuid()),
  recurrenceCycleStart: v.pipe(v.string(), v.isoDate()),
  scheduleDays: v.array(vScheduleDayIn),
});

export const vDayRedefinitionOut = v.object({
  date: v.pipe(v.string(), v.isoDate()),
  dayData: v.unknown(),
  masterId: v.pipe(v.string(), v.uuid()),
});

export const vDeleteNotificationTemplateRequest = v.object({
  templateId: v.pipe(v.string(), v.uuid()),
});

export const vEmployeeOut = v.object({
  contactEmail: v.string(),
  contactPhone: v.string(),
  contactTelegram: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  roles: v.array(vEmployeeRole),
  userId: v.pipe(v.string(), v.uuid()),
});

export const vMasterOut = v.object({
  contactEmail: v.optional(v.union([v.string(), v.null()])),
  contactPhone: v.optional(v.union([v.string(), v.null()])),
  contactTelegram: v.optional(v.union([v.string(), v.null()])),
  firstName: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  lastName: v.string(),
  patronymic: v.optional(v.union([v.string(), v.null()])),
});

export const vNotificationSettingsResponse = v.object({
  branchId: v.pipe(v.string(), v.uuid()),
  createdAt: v.string(),
  criticalThresholdHours: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
    v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
  ),
  quietHoursEnd: v.string(),
  quietHoursStart: v.string(),
  smartBoundaryHours: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
    v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
  ),
  updatedAt: v.string(),
});

export const vNotificationStatus = v.picklist([
  'pending',
  'sent',
  'failed',
  'cancelled',
]);

export const vNotificationTemplateResponse = v.object({
  body: v.string(),
  branchId: v.pipe(v.string(), v.uuid()),
  createdAt: v.string(),
  id: v.pipe(v.string(), v.uuid()),
  method: vNotifyMethod,
  templateType: vNotificationTemplateType,
  updatedAt: v.string(),
});

export const vOrganizationDashboardOut = v.object({
  active: v.boolean(),
  alLeastOneBranch: v.boolean(),
  alLeastOneMaster: v.boolean(),
  alLeastOneService: v.boolean(),
  alLeastOneTimetable: v.boolean(),
  description: v.string(),
  displayName: v.string(),
  id: v.string(),
  name: v.string(),
});

export const vOrganizationOut = v.object({
  description: v.string(),
  displayName: v.string(),
  id: v.string(),
  name: v.string(),
});

export const vPhoneLoginOk = v.object({
  message: v.string(),
});

export const vPhoneLoginRequest = v.object({
  phone: v.string(),
});

export const vPhoneVerifyRequest = v.object({
  code: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
    v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
    v.minValue(0),
  ),
  phone: v.string(),
});

export const vScheduleDayOut = v.object({
  dayData: v.unknown(),
  dayOrdinal: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
    v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
  ),
  masterId: v.pipe(v.string(), v.uuid()),
});

export const vScheduledNotificationResponse = v.object({
  actualSendAt: v.string(),
  bookingId: v.pipe(v.string(), v.uuid()),
  createdAt: v.string(),
  errorMessage: v.optional(v.union([v.string(), v.null()])),
  id: v.pipe(v.string(), v.uuid()),
  method: vNotifyMethod,
  scheduledAt: v.string(),
  sentAt: v.optional(v.union([v.string(), v.null()])),
  status: vNotificationStatus,
  updatedAt: v.string(),
});

export const vSendBulkNotificationRequest = v.intersect([
  vBulkRecipientStrategy,
  v.object({
    branchId: v.pipe(v.string(), v.uuid()),
    message: v.string(),
    method: vNotifyMethod,
    scheduledAt: v.optional(v.union([v.string(), v.null()])),
  }),
]);

export const vServiceOut = v.object({
  description: v.string(),
  durationMinutes: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
    v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
    v.minValue(0),
  ),
  id: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  price: v.optional(v.union([v.string(), v.null()])),
});

export const vTelegramAuthRequest = v.object({
  hash: v.string(),
});

export const vTelegramVerifyHash = v.object({
  hash: v.string(),
});

export const vTimetableOut = v.object({
  masterId: v.pipe(v.string(), v.uuid()),
  recurrenceCycleDays: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
    v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
  ),
  recurrenceCycleStart: v.pipe(v.string(), v.isoDate()),
});

export const vTimetableWithRedefinitionsOut = v.object({
  redefinitions: v.array(vDayRedefinitionOut),
  schedule_days: v.array(vScheduleDayOut),
  timetable: vTimetableOut,
});

export const vUpdateBranchRequest = v.object({
  addressInfo: v.optional(v.union([v.string(), v.null()])),
  apartmentNumber: v.optional(v.union([v.string(), v.null()])),
  city: v.optional(v.union([v.string(), v.null()])),
  country: v.optional(v.union([v.string(), v.null()])),
  description: v.optional(v.union([v.string(), v.null()])),
  houseNumber: v.optional(v.union([v.string(), v.null()])),
  name: v.optional(v.union([v.string(), v.null()])),
  region: v.optional(v.union([v.string(), v.null()])),
  street: v.optional(v.union([v.string(), v.null()])),
  timezone: v.optional(v.union([v.string(), v.null()])),
});

export const vUpdateEmployeeRequest = v.object({
  contactEmail: v.optional(v.union([v.string(), v.null()])),
  contactPhone: v.optional(v.union([v.string(), v.null()])),
  contactTelegram: v.optional(v.union([v.string(), v.null()])),
  roles: v.optional(v.union([v.array(vEmployeeRole), v.null()])),
  userId: v.optional(v.union([v.pipe(v.string(), v.uuid()), v.null()])),
});

export const vUpdateNotificationSettingsRequest = v.object({
  branchId: v.pipe(v.string(), v.uuid()),
  criticalThresholdHours: v.optional(
    v.union([
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
        v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
      ),
      v.null(),
    ]),
  ),
  quietHoursEnd: v.optional(v.union([v.string(), v.null()])),
  quietHoursStart: v.optional(v.union([v.string(), v.null()])),
  smartBoundaryHours: v.optional(
    v.union([
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
        v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
      ),
      v.null(),
    ]),
  ),
});

export const vUpdateNotificationTemplateRequest = v.object({
  body: v.optional(v.union([v.string(), v.null()])),
  method: v.optional(v.union([v.null(), vNotifyMethod])),
  templateId: v.pipe(v.string(), v.uuid()),
  templateType: v.optional(v.union([v.null(), vNotificationTemplateType])),
});

export const vUpdateProfileRequest = v.object({
  firstName: v.string(),
  lastName: v.string(),
  patronymic: v.optional(v.union([v.string(), v.null()])),
});

export const vUpdateServiceRequest = v.object({
  description: v.optional(v.union([v.string(), v.null()])),
  displayName: v.optional(v.union([v.string(), v.null()])),
  durationMinutes: v.optional(
    v.union([
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2^31'),
        v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2^31-1'),
      ),
      v.null(),
    ]),
  ),
  masterId: v.optional(v.union([v.pipe(v.string(), v.uuid()), v.null()])),
  price: v.optional(v.union([v.string(), v.null()])),
});

export const vUpdateTimetableRequest = v.object({
  recurrenceCycleStart: v.optional(
    v.union([v.pipe(v.string(), v.isoDate()), v.null()]),
  ),
  scheduleDays: v.optional(v.union([v.array(vScheduleDayIn), v.null()])),
});

export const vUserProfileResponse = v.object({
  firstName: v.string(),
  lastName: v.string(),
  patronymic: v.optional(v.union([v.string(), v.null()])),
});

export const vGetBookingNotificationsData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    booking_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Booking notifications retrieved
 */
export const vGetBookingNotificationsResponse = v.array(
  vScheduledNotificationResponse,
);

export const vListBranchesData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    organization_id: v.union([v.pipe(v.string(), v.uuid()), v.null()]),
    limit: v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
    offset: v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
  }),
  query: v.optional(v.never()),
});

/**
 * List of branches
 */
export const vListBranchesResponse = v.array(vBranchOut);

export const vCreateBranchData = v.object({
  body: vCreateBranchRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Branch created
 */
export const vCreateBranchResponse = vCreateBranchOut;

export const vDeleteBranchData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Branch deleted
 */
export const vDeleteBranchResponse = v.void();

export const vGetBranchData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Branch details
 */
export const vGetBranchResponse = vBranchOut;

export const vUpdateBranchData = v.object({
  body: vUpdateBranchRequest,
  path: v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Branch updated
 */
export const vUpdateBranchResponse = vBranchOut;

export const vGetNotificationSettingsData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Notification settings retrieved
 */
export const vGetNotificationSettingsResponse = vNotificationSettingsResponse;

export const vGetNotificationTemplatesData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Notification templates retrieved
 */
export const vGetNotificationTemplatesResponse = v.array(
  vNotificationTemplateResponse,
);

export const vGetNotificationTemplateData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
    template_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Notification template retrieved
 */
export const vGetNotificationTemplateResponse = vNotificationTemplateResponse;

export const vGetScheduledNotificationsData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    branch_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Scheduled notifications retrieved
 */
export const vGetScheduledNotificationsResponse = v.array(
  vScheduledNotificationResponse,
);

export const vGetOrganizationDashboardData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    organization_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Organization dashboard
 */
export const vGetOrganizationDashboardResponse = vOrganizationDashboardOut;

export const vListEmployeesData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(
    v.object({
      organization_id: v.optional(
        v.union([v.pipe(v.string(), v.uuid()), v.null()]),
      ),
      limit: v.optional(
        v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
      ),
      offset: v.optional(
        v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
      ),
    }),
  ),
});

/**
 * List of employees
 */
export const vListEmployeesResponse = v.array(vEmployeeOut);

export const vCreateEmployeeData = v.object({
  body: vCreateEmployeeRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Employee created
 */
export const vCreateEmployeeResponse = vCreateEmployeeOut;

export const vDeleteEmployeeData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    employee_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Employee deleted
 */
export const vDeleteEmployeeResponse = v.void();

export const vGetEmployeeData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    employee_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Employee details
 */
export const vGetEmployeeResponse = vEmployeeOut;

export const vUpdateEmployeeData = v.object({
  body: vUpdateEmployeeRequest,
  path: v.object({
    employee_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Employee updated
 */
export const vUpdateEmployeeResponse = vEmployeeOut;

export const vUpdateNotificationSettingsData = v.object({
  body: vUpdateNotificationSettingsRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Notification settings updated
 */
export const vUpdateNotificationSettingsResponse =
  vNotificationSettingsResponse;

export const vDeleteNotificationTemplateData = v.object({
  body: vDeleteNotificationTemplateRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Notification template deleted
 */
export const vDeleteNotificationTemplateResponse = v.void();

export const vCreateNotificationTemplateData = v.object({
  body: vCreateNotificationTemplateRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Notification template created
 */
export const vCreateNotificationTemplateResponse =
  vNotificationTemplateResponse;

export const vUpdateNotificationTemplateData = v.object({
  body: vUpdateNotificationTemplateRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Notification template updated
 */
export const vUpdateNotificationTemplateResponse =
  vNotificationTemplateResponse;

export const vCreateOrganizationData = v.object({
  body: vCreateOrganizationRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Organization created successfully
 */
export const vCreateOrganizationResponse = vOrganizationOut;

export const vSendBulkNotificationData = v.object({
  body: vSendBulkNotificationRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Bulk notification sent
 */
export const vSendBulkNotificationResponse = vBulkNotificationResponse;

export const vListServicesData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(
    v.object({
      organization_id: v.optional(
        v.union([v.pipe(v.string(), v.uuid()), v.null()]),
      ),
      limit: v.optional(
        v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
      ),
      offset: v.optional(
        v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
      ),
    }),
  ),
});

/**
 * List of services
 */
export const vListServicesResponse = v.array(vServiceOut);

export const vCreateServiceData = v.object({
  body: vCreateServiceRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Service created
 */
export const vCreateServiceResponse = vCreateServiceOut;

export const vDeleteServiceData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    service_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Service deleted
 */
export const vDeleteServiceResponse = v.void();

export const vGetServiceData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    service_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Service details
 */
export const vGetServiceResponse = vServiceOut;

export const vUpdateServiceData = v.object({
  body: vUpdateServiceRequest,
  path: v.object({
    service_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Service updated
 */
export const vUpdateServiceResponse = vServiceOut;

export const vListTimetablesData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(
    v.object({
      organization_id: v.optional(
        v.union([v.pipe(v.string(), v.uuid()), v.null()]),
      ),
      limit: v.optional(
        v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
      ),
      offset: v.optional(
        v.union([v.pipe(v.number(), v.integer(), v.minValue(0)), v.null()]),
      ),
    }),
  ),
});

/**
 * List of timetables
 */
export const vListTimetablesResponse = v.array(vTimetableOut);

export const vCreateTimetableData = v.object({
  body: vCreateTimetableRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Timetable created
 */
export const vCreateTimetableResponse = v.void();

export const vCreateDayRedefinitionData = v.object({
  body: vCreateDayRedefinitionRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Day redefinition created
 */
export const vCreateDayRedefinitionResponse = v.void();

export const vDeleteDayRedefinitionData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    master_id: v.pipe(v.string(), v.uuid()),
    date: v.pipe(v.string(), v.isoDate()),
  }),
  query: v.optional(v.never()),
});

/**
 * Day redefinition deleted
 */
export const vDeleteDayRedefinitionResponse = v.void();

export const vDeleteTimetableData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    master_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Timetable deleted
 */
export const vDeleteTimetableResponse = v.void();

export const vGetTimetableWithRedefinitionsData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    master_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Timetable with schedule days and redefinitions
 */
export const vGetTimetableWithRedefinitionsResponse =
  vTimetableWithRedefinitionsOut;

export const vUpdateTimetableData = v.object({
  body: vUpdateTimetableRequest,
  path: v.object({
    master_id: v.pipe(v.string(), v.uuid()),
  }),
  query: v.optional(v.never()),
});

/**
 * Timetable updated
 */
export const vUpdateTimetableResponse = vTimetableOut;

export const vLoginPhoneData = v.object({
  body: vPhoneLoginRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Verification code sent
 */
export const vLoginPhoneResponse = vPhoneLoginOk;

export const vLoginTelegramData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Hash for verification
 */
export const vLoginTelegramResponse = vTelegramVerifyHash;

export const vLogoutData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

export const vLogoutAllData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

export const vGetProfileData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Profile retrieved successfully
 */
export const vGetProfileResponse = vUserProfileResponse;

export const vUpdateProfileData = v.object({
  body: vUpdateProfileRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Profile updated successfully
 */
export const vUpdateProfileResponse = vUserProfileResponse;

export const vRefreshData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Token refreshed
 */
export const vRefreshResponse = vAccessToken;

export const vVerifyPhoneData = v.object({
  body: vPhoneVerifyRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Verification successful
 */
export const vVerifyPhoneResponse = vAccessToken;

export const vVerifyTelegramData = v.object({
  body: vTelegramAuthRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Verification successful
 */
export const vVerifyTelegramResponse = vAccessToken;

export const vCreateBookingData = v.object({
  body: vCreateBookingRequest,
  path: v.optional(v.never()),
  query: v.optional(v.never()),
});

/**
 * Booking created
 */
export const vCreateBookingResponse = v.array(vBookingOut);

export const vGetBranchesData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.object({
    organization_name: v.string(),
    'masters[]': v.array(v.pipe(v.string(), v.uuid())),
  }),
});

/**
 * List of branches
 */
export const vGetBranchesResponse = v.array(vBranchOut);

export const vGetMastersData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.object({
    organization_name: v.string(),
    'branches[]': v.array(v.pipe(v.string(), v.uuid())),
    'services[]': v.array(v.pipe(v.string(), v.uuid())),
  }),
});

/**
 * List of masters
 */
export const vGetMastersResponse = v.array(vMasterOut);

export const vGetMasterByIdData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    master_id: v.string(),
  }),
  query: v.optional(v.never()),
});

/**
 * Master with ID
 */
export const vGetMasterByIdResponse = vMasterOut;

export const vGetOrganizationByNameData = v.object({
  body: v.optional(v.never()),
  path: v.object({
    organization_name: v.string(),
  }),
  query: v.optional(v.never()),
});

/**
 * Organization with name
 */
export const vGetOrganizationByNameResponse = vOrganizationOut;

export const vGetServicesData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.object({
    organization_name: v.string(),
    'masters[]': v.array(v.pipe(v.string(), v.uuid())),
  }),
});

/**
 * List of services
 */
export const vGetServicesResponse = v.array(vServiceOut);

export const vGetWindowsData = v.object({
  body: v.optional(v.never()),
  path: v.optional(v.never()),
  query: v.object({
    organization_name: v.string(),
    service_id: v.pipe(v.string(), v.uuid()),
    'masters[]': v.array(v.pipe(v.string(), v.uuid())),
    'branches[]': v.array(v.pipe(v.string(), v.uuid())),
    min_datetime: v.pipe(v.string(), v.isoTimestamp()),
    max_datetime: v.pipe(v.string(), v.isoTimestamp()),
  }),
});

/**
 * List of branches
 */
export const vGetWindowsResponse = v.array(vBranchOut);
